[build]
functions = "backend/netlify/functions"
command = "npm install --prefix backend"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
